import Course from "../models/Course.js";
import CourseModule from "../models/CourseModule.js";
import CourseEnrollment from "../models/CourseEnrollment.js";

function getVisitorId(req) {
  // Prefer header; fallback to body
  return req.headers["x-visitor-id"] || req.body?.visitorId;
}

export const listCourses = async (req, res) => {
  try {
    const courses = await Course.findAll({
      where: { isActive: true },
      attributes: ["slug", "title", "description", "level", "coverImageUrl", "durationHours"],
      order: [["createdAt", "DESC"]],
    });
    res.json(courses);
  } catch (err) {
    console.error("listCourses error:", err);
    res.status(500).json({ message: "Server error" });
  }
};

export const getCourse = async (req, res) => {
  try {
    const { slug } = req.params;
    if (!slug || !String(slug).trim()) return res.status(400).json({ message: "slug is required" });

    const course = await Course.findOne({ where: { slug } });
    if (!course) return res.status(404).json({ message: "Course not found" });

    res.json(course);
  } catch (err) {
    console.error("getCourse error:", err);
    res.status(500).json({ message: "Server error" });
  }
};

export const listCourseModules = async (req, res) => {
  try {
    const { slug } = req.params;
    const modules = await CourseModule.findAll({
      where: { courseSlug: slug },
      order: [["orderIndex", "ASC"]],
      attributes: ["id", "title", "orderIndex", "content", "videoUrl", "quiz"],
    });
    res.json(modules);
  } catch (err) {
    console.error("listCourseModules error:", err);
    res.status(500).json({ message: "Server error" });
  }
};

export const enrollCourse = async (req, res) => {
  try {
    const { slug } = req.params;
    const visitorId = getVisitorId(req);
    const { fullName } = req.body || {};

    if (!slug || !String(slug).trim()) return res.status(400).json({ message: "slug is required" });
    if (!visitorId) return res.status(400).json({ message: "visitorId is required" });
    if (!fullName || !String(fullName).trim()) return res.status(400).json({ message: "fullName is required" });

    const normalizedFullName = String(fullName).trim();

    const course = await Course.findOne({ where: { slug } });
    if (!course) return res.status(404).json({ message: "Course not found" });

    const existing = await CourseEnrollment.findOne({
      where: { courseSlug: slug, visitorId },
    });

    if (existing) {
      existing.fullName = normalizedFullName;

      if (existing.status === "completed") {
        return res.json({ enrollment: existing, certificate: null, message: "Already completed" });
      }

      existing.status = "in_progress";
      await existing.save();

      return res.json({ enrollment: existing, certificate: null, message: "Enrollment updated" });
    }

    const enrollment = await CourseEnrollment.create({
      courseSlug: slug,
      fullName: normalizedFullName,
      visitorId,
      status: "in_progress",
    });

    res.json({ enrollment, certificate: null });
  } catch (err) {
    console.error("enrollCourse error:", err);
    res.status(500).json({
      message: "Server error",
      error: err?.message || err?.name || "Unknown error",
    });
  }
};

export const completeCourse = async (req, res) => {
  try {
    const { slug } = req.params;
    const visitorId = getVisitorId(req);
    const { fullName } = req.body || {};

    if (!visitorId) return res.status(400).json({ message: "visitorId is required" });
    if (!slug || !String(slug).trim()) return res.status(400).json({ message: "slug is required" });
    if (!fullName || !String(fullName).trim()) return res.status(400).json({ message: "fullName is required" });

    const course = await Course.findOne({ where: { slug } });
    if (!course) return res.status(404).json({ message: "Course not found" });

    const enrollment = await CourseEnrollment.findOne({ where: { courseSlug: slug, visitorId } });
    if (!enrollment) return res.status(400).json({ message: "Enroll first to complete" });

    enrollment.fullName = String(fullName).trim();
    enrollment.status = "completed";
    enrollment.completedAt = new Date();
    await enrollment.save();

    res.json({
      certificate: null,
      enrollment,
      message: "Enrollment completed. Certificate will be generated by admin.",
    });
  } catch (err) {
    console.error("completeCourse error:", err);
    res.status(500).json({
      message: "Server error",
      error: err?.message || err?.name || "Unknown error",
    });
  }
};

